version: "3.9"
services:
  backend2:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: node_backend2
    working_dir: /app/backend
    ports:
      - "4050:3000"
    env_file:
      - ./backend/.env
    restart: always
    networks:
      - default
